templates = {
    'portrait': './templates/portrait.svg',
    'straight_fringe': './templates/fhair_1.svg',
    'straight_fringe2': './templates/fhair_3.svg',
    'straight_fringe3': './templates/fhair_5.svg',
    'tied_fringe': './templates/fhair_2.svg',
    'spiky_fringe': './templates/fhair_4.svg',
    'buzz_cut': './templates/fhair_6.svg',
    'army': './templates/fhair_7.svg',
    'short_sides': './templates/fhair_8.svg',
    'pompadour': './templates/fhair_9.svg',
    'curly_fringe': './templates/fhair_10.svg',
    'short_square': './templates/fhair_12.svg',
    'tied_braids': './templates/fhair_13.svg',
    'dread_locks': './templates/fhair_14.svg',
    'loose_straight': './templates/bhair_1.svg',
    'short_straight': './templates/bhair_4.svg',
    'bun': './templates/bhair_2.svg',
    'spiky_back': './templates/bhair_3.svg',
    'curly_back': './templates/bhair_5.svg',
    'afro_back_1': './templates/bhair_6.svg',
    'afro_back_2': './templates/bhair_7.svg',
    'small_dlocks_back': './templates/bhair_8.svg',
}
default_descriptors = {
    'cheek': (0.3, 0.18),
    'cheek_low': lambda d: d['cheek'] * 2 if d['cheek'] < 0.5 else 0,
    'cheek_high': lambda d: (d['cheek'] - 0.5) * 2 if d['cheek'] > 0.5 else 0,
    'chin': (0.5, 0.15),
    'ear_size': (0.0, 0.3),
    'eye_size': (0.25, 0.12),
    'eye_height': (0.5, 0.2),
}